# Generated by Django 3.1.7 on 2023-01-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_sportsmans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtemplate',
            options={'verbose_name': 'Шаблон тестирования', 'verbose_name_plural': 'Шаблоны тестирований'},
        ),
    ]
