# Generated by Django 3.2.22 on 2023-12-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Прямая ссылка')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала события')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
