# Generated by Django 3.1.7 on 2022-06-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInformationNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('short_body', models.TextField(blank=True, null=True, verbose_name='Тело')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Тело')),
                ('archive_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата архивации')),
                ('published_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата публикации')),
                ('is_hidden', models.BooleanField(default=True, verbose_name='Скрыт')),
            ],
            options={
                'verbose_name': 'Групповое уведомления',
                'verbose_name_plural': 'Групповые Уведомления',
            },
        ),
        migrations.CreateModel(
            name='PersonalInformationNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('short_body', models.TextField(blank=True, null=True, verbose_name='Тело')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Тело')),
                ('archive_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата архивации')),
                ('published_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата публикации')),
                ('is_hidden', models.BooleanField(default=True, verbose_name='Скрыт')),
            ],
            options={
                'verbose_name': 'Персональное уведомления',
                'verbose_name_plural': 'Персональные Уведомления',
            },
        ),
    ]
