# Generated by Django 3.2.22 on 2023-12-18 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('is_win', models.BooleanField(default=False, verbose_name='Является верным')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во баллов')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответотв',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст вопроса')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('win_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во баллов')),
                ('allow_incorrect_answers', models.BooleanField(default=False, verbose_name='Допускать неверные ответы')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
            },
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(verbose_name='Постоянная ссылка')),
                ('is_open', models.BooleanField(default=False, verbose_name='Является открытым')),
                ('is_published', models.BooleanField(default=False, verbose_name='Является опубликованным')),
                ('max_win_score', models.IntegerField(blank=True, null=True, verbose_name='Максимальный балл')),
            ],
            options={
                'verbose_name': 'Шаблон тестирования',
                'verbose_name_plural': 'Шаблоны тестирований',
            },
        ),
        migrations.CreateModel(
            name='ResultTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('result_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во баллов')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_tests', to='testing.testtemplate', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
                'unique_together': {('test', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ResultQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question', verbose_name='Вопрос')),
                ('result_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.resulttest', verbose_name='Результат тестирования')),
            ],
            options={
                'verbose_name': 'Ответы на вопрос',
                'verbose_name_plural': 'Ответы на вопрос',
                'unique_together': {('result_test', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('answers', models.ManyToManyField(to='testing.Answer', verbose_name='Ответы')),
                ('result_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.resultquestion', verbose_name='Результат тестирования')),
            ],
            options={
                'verbose_name': 'Ответы на вопрос',
                'verbose_name_plural': 'Ответы на вопрос',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.testtemplate', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('html', models.TextField(blank=True, null=True, verbose_name='html код')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_objects', to='testing.question', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Медиа объект',
                'verbose_name_plural': 'Медиа объекты',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.question', verbose_name='Тест'),
        ),
    ]
