# Generated by Django 3.2.22 on 2023-10-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtemplate',
            name='max_win_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный балл'),
        ),
    ]
