# Generated by Django 3.2.22 on 2024-02-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20240224_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='testtemplate',
            name='date_created',
        ),
    ]
