# Generated by Django 3.1.7 on 2022-06-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(verbose_name='Постоянная ссылка')),
                ('is_open', models.BooleanField(default=False, verbose_name='Является открытым')),
                ('is_published', models.BooleanField(default=False, verbose_name='Является опубликованным')),
            ],
            options={
                'verbose_name': 'Шаблон тест',
                'verbose_name_plural': 'Шаблоны тестов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст вопроса')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('win_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во баллов')),
                ('allow_incorrect_answers', models.BooleanField(default=False, verbose_name='Допускать неверные ответы')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing_templates.testtemplate', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
            },
        ),
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('html', models.TextField(blank=True, null=True, verbose_name='html код')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_objects', to='testing_templates.question', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Медиа объект',
                'verbose_name_plural': 'Медиа объекты',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('is_win', models.BooleanField(default=False, verbose_name='Является верным')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во баллов')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing_templates.question', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответотв',
            },
        ),
    ]
