# Generated by Django 3.2.22 on 2023-12-18 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ekp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Обследование',
                'verbose_name_plural': 'Обследования',
            },
        ),
        migrations.CreateModel(
            name='ExaminationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('scheme', models.JSONField(blank=True, null=True, verbose_name='Схема ограничений ввода')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Является опубликованным')),
            ],
            options={
                'verbose_name': 'Шаблон медицинского обследования',
                'verbose_name_plural': 'Шаблоны медицинских обследований',
            },
        ),
        migrations.CreateModel(
            name='GroupIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Краткое наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа медецинских показателей',
                'verbose_name_plural': 'Группы медецинских показателей',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type_indicator', models.PositiveIntegerField(choices=[(1, 'Целочисленный'), (2, 'С плавающей точкой')], verbose_name='Type Indicator')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='ResultExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='результат обследования')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examination.examination', verbose_name='Обследование')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_examination', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_indicators', to='examination.examinationtemplate', verbose_name='Обследование')),
            ],
            options={
                'verbose_name': 'Результат обследования',
                'verbose_name_plural': 'Результат обследований',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Краткое наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='ResultIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='результат обследования')),
                ('group_indicators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_indicators', to='examination.groupindicators', verbose_name='Группа показателя')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_indicators', to='examination.indicator', verbose_name='Показатель')),
                ('result_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_indicators', to='examination.resultexamination', verbose_name='Обследование')),
            ],
            options={
                'verbose_name': 'Результат показателя',
                'verbose_name_plural': 'Результат показателей',
            },
        ),
        migrations.CreateModel(
            name='IndicatorWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1, verbose_name='Значение')),
                ('max_limit_value', models.FloatField(blank=True, null=True, verbose_name='Максимальное значение')),
                ('min_limit_value', models.FloatField(blank=True, null=True, verbose_name='Минимальное значение')),
                ('last_update_value', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновленеие значения')),
                ('last_update_limits', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновленеие пределов')),
                ('examination_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_weights', to='examination.examinationtemplate', verbose_name='Показатель')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_weights', to='examination.indicator', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Вес показателя',
                'verbose_name_plural': 'Веса показателей',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='groupindicators',
            name='indicators',
            field=models.ManyToManyField(to='examination.Indicator', verbose_name='Показатели'),
        ),
        migrations.CreateModel(
            name='GroupExaminations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekp.event', verbose_name='Событие')),
                ('examinations', models.ManyToManyField(to='examination.Examination', verbose_name='Обследования')),
            ],
            options={
                'verbose_name': 'Группа обследований',
                'verbose_name_plural': 'Группы обследований',
            },
        ),
        migrations.AddField(
            model_name='examinationtemplate',
            name='groups_indicators',
            field=models.ManyToManyField(to='examination.GroupIndicators', verbose_name='Группа показателей'),
        ),
    ]
