# Generated by Django 3.1.7 on 2021-09-04 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examination_templates', '0002_auto_20210706_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата обследования')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination_templates.examinationtemplate', verbose_name='Шаблон обследования')),
            ],
            options={
                'verbose_name': 'Обследование',
                'verbose_name_plural': 'Обследования',
            },
        ),
        migrations.CreateModel(
            name='GroupExaminations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('examinations', models.ManyToManyField(to='examination.Examination', verbose_name='Обследования')),
            ],
            options={
                'verbose_name': 'Группа обследований',
                'verbose_name_plural': 'Группы обследований',
            },
        ),
    ]
