# Generated by Django 3.1.7 on 2021-09-04 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='sportsman',
        ),
        migrations.AddField(
            model_name='examination',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.event', verbose_name='Событие'),
        ),
    ]
