# Generated by Django 3.2.22 on 2023-10-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_alter_resultexaminations_examination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='template',
        ),
        migrations.AddField(
            model_name='examination',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала события'),
        ),
        migrations.AddField(
            model_name='examination',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала события'),
        ),
    ]
