# Generated by Django 3.2.22 on 2024-02-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20231222_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationTemplateIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_template_indicators', to='examination.examinationtemplate', verbose_name='Шаблон обследования')),
                ('group_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_template_indicators', to='examination.groupindicators', verbose_name='Группа показателей')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_template_indicators', to='examination.indicator', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Показатель шаблона обследований',
                'verbose_name_plural': 'Показатели шаблона обследований',
            },
        ),
    ]
