# Generated by Django 3.2.22 on 2024-03-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_examinationtemplateindicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория медецинских показателей',
                'verbose_name_plural': 'Категории медецинских показателей',
            },
        ),
        migrations.RemoveField(
            model_name='examinationtemplate',
            name='groups_indicators',
        ),
        migrations.AlterField(
            model_name='examinationtemplateindicators',
            name='group_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_template_indicators', to='examination.groupindicators', verbose_name='Группа показателей'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='category_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='examination.categoryindicators', verbose_name='Группа показателей'),
        ),
    ]
