# Generated by Django 3.2.22 on 2023-11-08 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examination', '0003_auto_20231023_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultexaminations',
            name='sportsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_examination', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен'),
        ),
    ]
