# Generated by Django 3.1.7 on 2021-10-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_resultexaminations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexaminations',
            name='examinations',
            field=models.ManyToManyField(blank=True, null=True, to='examination.Examination', verbose_name='Обследования'),
        ),
    ]
