# Generated by Django 3.2.22 on 2024-03-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_auto_20240304_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_property',
            field=models.BooleanField(default=False, verbose_name='Является вычисляемым свойством'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='property_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='property_function',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Функция'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='value_property_indicator',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Абсолютное'), (2, 'Верхний порог'), (3, 'Нижний порог')], null=True, verbose_name='Type Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='type_indicator',
            field=models.PositiveIntegerField(choices=[(1, 'Целочисленный'), (2, 'С плавающей точкой'), (3, 'Является нормой'), (4, 'Процентное значение')], verbose_name='Type Indicator'),
        ),
    ]
