# Generated by Django 3.1.7 on 2021-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_auto_20211009_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexaminations',
            name='examinations',
            field=models.ManyToManyField(blank=True, to='examination.Examination', verbose_name='Обследования'),
        ),
    ]
