# Generated by Django 3.2.22 on 2023-11-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examination', '0004_alter_resultexaminations_sportsman'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1, verbose_name='Значение')),
                ('max_limit_value', models.FloatField(blank=True, null=True, verbose_name='Максимальное значение')),
                ('min_limit_value', models.FloatField(blank=True, null=True, verbose_name='Минимальное значение')),
                ('last_update_value', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновленеие значения')),
                ('last_update_limits', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновленеие пределов')),
                ('examination_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_weights', to='examination.examinationtemplate', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='ResultExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='результат обследования')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examination.examination', verbose_name='Обследование')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_examination', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_indicators', to='examination.examinationtemplate', verbose_name='Обследование')),
            ],
            options={
                'verbose_name': 'Результат обследования',
                'verbose_name_plural': 'Результат обследований',
            },
        ),
        migrations.CreateModel(
            name='ResultIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='результат обследования')),
                ('result_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_indicators', to='examination.resultexamination', verbose_name='Обследование')),
            ],
            options={
                'verbose_name': 'Результат показателя',
                'verbose_name_plural': 'Результат показателей',
            },
        ),
        migrations.AlterField(
            model_name='indicator',
            name='type_indicator',
            field=models.PositiveIntegerField(choices=[(1, 'Целочисленный'), (2, 'С плавающей точкой')], verbose_name='Type Indicator'),
        ),
        migrations.DeleteModel(
            name='ResultExaminations',
        ),
        migrations.AddField(
            model_name='indicatorweight',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_weights', to='examination.indicator', verbose_name='Показатель'),
        ),
    ]
