# Generated by Django 3.1.7 on 2021-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_auto_20211011_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexaminations',
            name='examinations',
            field=models.ManyToManyField(to='examination.Examination', verbose_name='Обследования'),
        ),
    ]
