# Generated by Django 3.1.7 on 2022-05-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0008_auto_20220529_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='groupexaminations',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='groupexaminations',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='resultexaminations',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resultexaminations',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование'),
        ),
    ]
