# Generated by Django 3.1.7 on 2021-08-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_examination_templates_manager',
            field=models.BooleanField(default=False, verbose_name='User is examination templates manager'),
        ),
    ]
