# Generated by Django 3.1.7 on 2021-08-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_examination_templates_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Пользователь является сотрудником'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sportsman',
            field=models.BooleanField(default=False, verbose_name='Пользователь является спортсменом'),
        ),
    ]
