# Generated by Django 3.2.22 on 2024-02-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(default=dict, verbose_name='Настройки клиента'),
        ),
    ]
