# Generated by Django 3.2.22 on 2024-03-09 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20240309_0508'),
        ('users', '0005_user_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_examination_templates_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='sportsman_organiztion_child_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.childgroup', verbose_name='Подгруппа'),
        ),
        migrations.AddField(
            model_name='user',
            name='sportsman_organiztion_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.educationgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(default={}, verbose_name='Настройки клиента'),
        ),
    ]
