@startuml Examination

title "Диаграмма классов "Обследования – Examination""


class Event {
    '
    id: Integer
    name: String
    description: String
}

class Examination {
    id: Integer
    name: String
    description: String
    template_id: Integer
    event_id: String
    date: Date
}

class GroupExaminations {
    id: Integer
    name: String
    description: String
    slug: String
}

class ResultExaminations {
    id: Integer
    examination_id: Integer
    sportsman_id: String
    result: Json
}

Examination *-left- Event
Examination *-right-* GroupExaminations
ResultExaminations *-down- Examination

@enduml
