
@startuml Testing

title "Диаграмма классов "Тестирование – Testing""


class ResultTesting {
    '
    id: Integer
    test_id: Integer
    sportsman_id: String
    result_score: Integer
}

class QuestionTesting {
    '
    id: Integer
    result_testing_id: Integer
    question_id: Integer
}

class AnswerTesting {
    '
    id: Integer
    question_testing_id: Integer
    answers: List
}



ResultTesting -right-* QuestionTesting
QuestionTesting -right-* AnswerTesting

@enduml
