# Generated by Django 3.2.22 on 2024-02-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0003_auto_20240222_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o002',
            name='rfkis_inn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o002',
            name='rfkis_ogrn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
