# Generated by Django 3.2.22 on 2024-02-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=25, verbose_name='Код')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Является актуальным')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='SportDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=25, verbose_name='Код')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Является актуальным')),
                ('sport_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_disciplines', to='competitions.sportcategory', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
    ]
