# Generated by Django 3.2.22 on 2023-10-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sporttype',
            options={'verbose_name': 'Вид спорта', 'verbose_name_plural': 'Виды спорта'},
        ),
        migrations.AlterField(
            model_name='sporttype',
            name='code_id',
            field=models.CharField(max_length=25, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='sporttype',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
    ]
