# Generated by Django 3.2.22 on 2024-03-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportdiscipline',
            options={'verbose_name': 'Спортивная дисциплина', 'verbose_name_plural': 'Спортивные дисциплина'},
        ),
    ]
