# Generated by Django 3.2.22 on 2023-10-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20231019_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttype',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Является актуальным'),
        ),
    ]
