# Generated by Django 3.1.7 on 2023-01-21 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала события')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата обследования')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination_sportsmans.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Обследование',
                'verbose_name_plural': 'Обследования',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Краткое наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='ResultExaminations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='результат обследования')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination_sportsmans.examination', verbose_name='Обследование')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Группа обследований',
                'verbose_name_plural': 'Группы обследований',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type_indicator', models.PositiveIntegerField(choices=[(1, 'Целое'), (2, 'Float')], verbose_name='Type Indicator')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination_sportsmans.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Medical Indicator',
                'verbose_name_plural': "Medical Indicator's",
            },
        ),
        migrations.CreateModel(
            name='GroupIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Краткое наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('indicators', models.ManyToManyField(to='examination_sportsmans.Indicator', verbose_name='Показатели')),
            ],
            options={
                'verbose_name': 'Группа медецинских показателей',
                'verbose_name_plural': 'Группы медецинских показателей',
            },
        ),
        migrations.CreateModel(
            name='GroupExaminations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('examinations', models.ManyToManyField(to='examination_sportsmans.Examination', verbose_name='Обследования')),
            ],
            options={
                'verbose_name': 'Группа обследований',
                'verbose_name_plural': 'Группы обследований',
            },
        ),
        migrations.CreateModel(
            name='ExaminationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('scheme', models.JSONField(blank=True, null=True, verbose_name='Схема ограничений ввода')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Является опубликованным')),
                ('groups_indicators', models.ManyToManyField(to='examination_sportsmans.GroupIndicators', verbose_name='Группа показателей')),
            ],
            options={
                'verbose_name': 'Шаблон медицинского обследования',
                'verbose_name_plural': 'Шаблоны медицинских обследований',
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination_sportsmans.examinationtemplate', verbose_name='Шаблон обследования'),
        ),
    ]
