# Generated by Django 3.1.7 on 2023-01-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination_sportsmans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Показатель', 'verbose_name_plural': 'Показатели'},
        ),
    ]
