# Generated by Django 3.1.7 on 2021-03-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': "Unit's",
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_indicator', models.PositiveIntegerField(choices=[(1, 'Целое'), (2, 'Float')], verbose_name='Type Medical Indicator')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination_templates.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Medical Indicator',
                'verbose_name_plural': "Medical Indicator's",
            },
        ),
    ]
