# Generated by Django 3.1.7 on 2021-07-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='type_indicator',
            field=models.PositiveIntegerField(choices=[(1, 'Целое'), (2, 'Float')], verbose_name='Type Indicator'),
        ),
        migrations.CreateModel(
            name='GroupIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('indicators', models.ManyToManyField(to='examination_templates.Indicator')),
            ],
            options={
                'verbose_name': 'Group of medical indicators',
                'verbose_name_plural': 'Group of medical indicators',
            },
        ),
        migrations.CreateModel(
            name='ExaminationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('groups_indicators', models.ManyToManyField(to='examination_templates.GroupIndicators')),
            ],
            options={
                'verbose_name': 'Medical Examination Template',
                'verbose_name_plural': "Medical Examination Template's",
            },
        ),
    ]
