# Generated by Django 3.1.7 on 2021-09-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_templates', '0002_auto_20210706_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinationtemplate',
            options={'verbose_name': 'Шаблон медицинского обследования', 'verbose_name_plural': 'Шаблоны медицинских обследований'},
        ),
        migrations.AddField(
            model_name='examinationtemplate',
            name='scheme',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема'),
        ),
    ]
