# Generated by Django 3.1.7 on 2022-05-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_templates', '0003_auto_20210905_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationtemplate',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='examinationtemplate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='examinationtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='groupindicators',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='groupindicators',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='groupindicators',
            name='short_name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='short_name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Краткое наименование'),
        ),
    ]
